package sabate.albert.todolist.Domain;

import java.util.Calendar;
import java.util.Date;

import sabate.albert.todolist.Exceptions.InvalidDateLimitThrowable;
import sabate.albert.todolist.Exceptions.NullIdThrowable;
import sabate.albert.todolist.Exceptions.NoNameThrowable;
import sabate.albert.todolist.Exceptions.TagCreatorThrowable;
import sabate.albert.todolist.Exceptions.NoDateOfCreationThrowable;

public class Tag {

    /* primary key, not null and automatically generated by the database */
    private Long id;
    /* not null */
    private String name;
    /* not null */
    private Date dateOfCreation;
    /* --- */
    private Date dateLimit;
    /* not null */
    private Boolean done;

    public Tag() {}

    /* This constructor doesn't initialize the id, it must be set in the controller */
    public Tag(String name, Date dateOfCreation, Date dateLimit) throws TagCreatorThrowable {
        if(name == null || name.isEmpty())
            throw new NoNameThrowable();
        if(dateOfCreation == null)
            throw new NoDateOfCreationThrowable();
        if(dateLimit != null && dateLimit.compareTo(Calendar.getInstance().getTime()) < 0)
            throw new InvalidDateLimitThrowable();
        this.name = name;
        this.dateOfCreation = dateOfCreation;
        this.dateLimit = dateLimit;
        this.done = false;
    }

    public long getId() {
        return id;
    }

    public void setId(Long id) throws NullIdThrowable {
        if(id == null)
            throw new NullIdThrowable();
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) throws NoNameThrowable {
        if(name == null || name.isEmpty())
            throw new NoNameThrowable();
        this.name = name;
    }

    public Date getDateOfCreation() {
        return dateOfCreation;
    }

    public void setDateOfCreation(Date dateOfCreation) throws NoDateOfCreationThrowable {
        if(dateOfCreation == null)
            throw new NoDateOfCreationThrowable();
        this.dateOfCreation = dateOfCreation;
    }

    public Date getDateLimit() {
        return dateLimit;
    }

    public void setDateLimit(Date dateLimit) throws InvalidDateLimitThrowable {
        if(dateLimit != null && dateLimit.compareTo(Calendar.getInstance().getTime()) < 0)
            throw new InvalidDateLimitThrowable();
        this.dateLimit = dateLimit;
    }

    public Boolean getDone() {
        return done;
    }

    public void setDone(Boolean done) {
        if(done == null) done = false;
        this.done = done;
    }

}
